### PR TITLE
Fix: hosts default + client gem 7.x compatibility

### LINKED ISSUE #125: Default setting for "hosts" not working
Running logstash and elasticsearch on the same host, I wanted to use the default configuration for "hosts" of the elasticsearch filter plugin by simply omitting to explicit set a value for "hosts", i.e. it should implicitly use ["localhost:9200"].

However, logstash cannot successfully connect and instead throws an error message, it seems the actual default value in the code is ["//localhost:9200"] so that the URL built does not contain a valid host name, i.e. the URL ends up to be http:////localhost:9200 (with four backslashes).

`[2020-02-25T16:49:38,156][INFO ][logstash.filters.elasticsearch][main] New ElasticSearch filter client {:hosts=>["//localhost:9200"]}

[2020-02-25T16:49:38,221][ERROR][logstash.javapipeline    ][main] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Manticore::ClientProtocolException: URI does not specify a valid host name: http:////localhost:9200/>, :backtrace=>["/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:37:in `block in initialize'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:79:in `call'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:274:in `call_once'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:158:in `code'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/manticore.rb:84:in `block in perform_request'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/manticore.rb:67:in `perform_request'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/client.rb:131:in `perform_request'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-api-5.0.5/lib/elasticsearch/api/actions/ping.rb:20:in `ping'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.7.0/lib/logstash/filters/elasticsearch.rb:270:in `test_connection!'", "/root/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.7.0/lib/logstash/filters/elasticsearch.rb:92:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:56:in `register'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:200:in `block in register_plugins'", "org/jruby/RubyArray.java:1814:in `each'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:199:in `register_plugins'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:502:in `maybe_setup_out_plugins'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:212:in `start_workers'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:154:in `run'", "/root/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:109:in `block in start'"], "pipeline.sources"=>["/root/logstash-7.6.0/bin/my-config.conf"], :thread=>"#<Thread:0xb784414 run>"}`

Logstash 7.6.0 on CentOS 8, logstash-filter-elasticsearch version 3.7.0

Filter plugin config section:

`        elasticsearch {
                query => "_id:%{[my_document_id]}"
                fields => { "[last_trust_decision][result]" => "old_result" }
                index => "my-index"
        }
`

### LINKED ISSUE #129: Illegal character in authority at index 8
I' trying to use this filter plugin. When i run the it with logstash 7.6.2 and newest filter version 3.7.1, I receive the following error:

`[WARN ] 2020-04-16 09:05:18.073 [[main]>worker1] elasticsearch - Failed to query elasticsearch for previous event {:index=>"proxy-blacklist", :error=>"Illegal character in authority at index 8: https://{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>{:host=>\"elastic01.example.org\", :scheme=>\"https\", :protocol=>\"https\", :port=>9200}, :scheme=>\"https\", :protocol=>\"https\", :port=>9200}, :scheme=>\"https\", :protocol=>\"https\", :port=>9200}, :scheme=>\"https\", :protocol=>\"https\", :port=>9200}, :scheme=>\"https\"}, :scheme=>\"https\"}, :scheme=>\"https\"}, :scheme=>\"https\", :protocol=>\"https\", :port=>9200}, :scheme=>\"https\"}, :scheme=>\"https\"}, :scheme=>\"https\"}, :scheme=>\"https\", :protocol=>\"https\", :port=>9200}, :scheme=>\"https\"}, :scheme=>\"https\"}, :scheme=>\"https\", :protocol=>\"https\", :port=>9200}, :scheme=>\"https\", :protocol=>\"https\", :port=>9200}, :scheme=>\"https\"}, :scheme=>\"https\"}:9200/proxy-blacklist/_search?q=domain.keyword%3A%2F%28www.%29%3Fchat.example.org%2F&size=1&sort=%40timestamp%3Adesc"}`

So it comes down to:

`Illegal character in authority at index 8`

I've found many users which seem to have this problem but no solution at all. Some solve this by not using "ssl => true" and using the prefix "https://" in the hosts section instead. This does not solve the error for me. My filter config looks like this:

> filter {
>   grok {
>     patterns_dir => [ "/etc/logstash/patterns/patterns" ]
>     match       => [ "message", "%{SQUIDACCESS}" ]
>   }
>   elasticsearch {
>     hosts               => [ "elastic.example.org" ]
>     user                => "elastic"
>     password            => "changeme"
>     ssl                 => true
>     ca_file             => "/etc/logstash/ca.crt"
>     index               => "blacklist"
>     query               => "domain.keyword:/(www.)?%{zone}/"
>     fields              => { "domid" => "domid" }
>     fields              => { "source" => "source" }
>   }
> }

### LINKED ISSUE #147: does not work properly with updated ES client
**Logstash information**:

Please include the following information:

Logstash version (e.g. `bin/logstash --version`) **7.14.0**

**Description of the problem including expected versus actual behavior**:

The problem relates to a elasticsearch client dependency update, for LS < 7.14.0 the version used was 5.0.5, 
in 7.14.0 LS forced a requirement of `>7` and ended up with version 7.5.0 which does not work properly.

**Steps to reproduce**:

`bin/logstash -e "filter { elasticsearch { user => 'elastic' password => 'elastic' hosts => 'http://localhost:9200' } }"`

NOTE: `hosts` needed due broken default on the field: https://github.com/logstash-plugins/logstash-filter-elasticsearch/issues/125

**Provide logs (if relevant)**:

**7.13.0** works while **7.14.0** fails with 401 (failing to pass basic auth header):
```
[2021-08-10T11:34:59,488][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.14.0", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 25.302-b08 on 1.8.0_302-b08 +indy +jit [linux-x86_64]"}
[2021-08-10T11:34:59,537][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/home/kares/workspace/work/elastic/logstash-7.14.0/data/queue"}
[2021-08-10T11:34:59,557][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/home/kares/workspace/work/elastic/logstash-7.14.0/data/dead_letter_queue"}
[2021-08-10T11:35:00,147][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2021-08-10T11:35:00,201][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"f07279a0-4967-4ef8-b508-ba191b55fefb", :path=>"/home/kares/workspace/work/elastic/logstash-7.14.0/data/uuid"}
[2021-08-10T11:35:03,573][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9601}
[2021-08-10T11:35:04,668][INFO ][org.reflections.Reflections] Reflections took 167 ms to scan 1 urls, producing 120 keys and 417 values 
[2021-08-10T11:35:09,507][INFO ][logstash.filters.elasticsearch][main] New ElasticSearch filter client {:hosts=>["http://localhost:9200"]}
[2021-08-10T11:35:10,466][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Elasticsearch::Transport::Transport::Errors::Unauthorized: [401] >, :backtrace=>["/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/transport/http/manticore.rb:71:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.5.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/elasticsearch-api-7.5.0/lib/elasticsearch/api/actions/ping.rb:23:in `ping'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.9.3/lib/logstash/filters/elasticsearch.rb:310:in `test_connection!'", "/home/kares/workspace/work/elastic/logstash-7.14.0/vendor/bundle/jruby/2.5.0/gems/logstash-filter-elasticsearch-3.9.3/lib/logstash/filters/elasticsearch.rb:117:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in `register'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1820:in `each'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:586:in `maybe_setup_out_plugins'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:240:in `start_workers'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/home/kares/workspace/work/elastic/logstash-7.14.0/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["config string"], :thread=>"#<Thread:0x6c7c724f run>"}
[2021-08-10T11:35:10,470][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
```

### PR DESCRIPTION
**Pull request by kares**
These changes primarily fix the [regression in LS 7.14.0](https://github.com/elastic/logstash/issues/13122) where due the elasticsearch client update (from 5.0.5 to 7.5.0) the `Authorization` header isn't passed (due a [bug](https://github.com/elastic/elasticsearch-ruby/issues/1428) in client versions 7.2.0 - 7.14.0). This leads to the plugin not being able to leverage `user`/`password` credentials set by the user to connect to ES.

The fix involves a patch to work-around the elasticsearch client issue.
Docker was adjusted to be able to run ES secured with $ELASTIC_PASSWORD for the *elastic* user (for integration tests).

---

We're also fixing a small issue that I've run into where omitting the `hosts` option wasn't working properly (with the `localhost:9200` default) and another plugin bug due `@hosts` variable mutation (from multiple workers).

resolves #147
resolves #125
resolves #129 (closes https://github.com/logstash-plugins/logstash-filter-elasticsearch/pull/133)

### CODE REVIEW

File: lib/logstash/filters/elasticsearch/patch.rb [hunk 1]
```diff
@@ -0,0 +1,26 @@
+# encoding: utf-8
+require "elasticsearch"
+require "elasticsearch/transport/transport/http/manticore"
+
+es_client_version = Gem.loaded_specs['elasticsearch-transport'].version
+if es_client_version >= Gem::Version.new('7.2') && es_client_version < Gem::Version.new('7.15')
```
Comment (kares) [inline lib/logstash/filters/elasticsearch/patch.rb:6]: we're assuming elasticsearch client would resolve the issue in 7.15.0, otherwise this will need to be revisited

**Review by andsel — APPROVED** [review]
LGTM

Tested locally with LS `7.13.4` and `7.14.0` and works great!
Good catch
